version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - THUMBNAIL_MAX_SIDE=${THUMBNAIL_MAX_SIDE:-1024}
    ports:
      - "8000:8000"
    networks:
      - appnet

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - NEXT_PUBLIC_BACKEND_BASE=http://backend:8000
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - NEXT_PUBLIC_GOOGLE_API_KEY=${NEXT_PUBLIC_GOOGLE_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge 