FROM nvidia/cuda:12.3.2-runtime-ubuntu22.04
RUN apt-get update && apt-get install -y \
    python3-pip \
    libcairo2-dev \
    libgirepository1.0-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 80
CMD ["uvicorn","api:app","--host","0.0.0.0","--port","80"]
