version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports: ["80:80"]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped 