FROM nvidia/cuda:12.3.2-runtime-ubuntu22.04
RUN apt-get clean && rm -rf /var/lib/apt/lists/* && \
    apt-get update --fix-missing || apt-get update && \
    apt-get install -y python3-pip libcairo2-dev libgirepository1.0-dev && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python3","worker.py"] 